<p><label for="<?php echo $this->get_field_id('name'); ?>"><?php echo __('Name'); ?>: <input class="widefat" id="<?php echo $this->get_field_id('name'); ?>" name="<?php echo $this->get_field_name('name'); ?>" type="text" value="<?php echo attribute_escape($name); ?>" /></label></p>
<p><label for="<?php echo $this->get_field_id('picture'); ?>"><?php echo __('Picture'); ?>: <input class="widefat" id="<?php echo $this->get_field_id('picture'); ?>" name="<?php echo $this->get_field_name('picture'); ?>" type="text" value="<?php echo attribute_escape($picture); ?>" /></label></p>
<p><label for="<?php echo $this->get_field_id('width'); ?>"><?php echo __('Picture width'); ?>: <input class="widefat" id="<?php echo $this->get_field_id('width'); ?>" name="<?php echo $this->get_field_name('width'); ?>" type="text" value="<?php echo attribute_escape($width); ?>" /></label></p>
<p><label for="<?php echo $this->get_field_id('twitter'); ?>"><?php echo __('Twitter link'); ?>: <input class="widefat" id="<?php echo $this->get_field_id('twitter'); ?>" name="<?php echo $this->get_field_name('twitter'); ?>" type="text" value="<?php echo attribute_escape($twitter); ?>" /></label></p>
<p><label for="<?php echo $this->get_field_id('facebook'); ?>"><?php echo __('Facebook link'); ?>: <input class="widefat" id="<?php echo $this->get_field_id('facebook'); ?>" name="<?php echo $this->get_field_name('facebook'); ?>" type="text" value="<?php echo attribute_escape($facebook); ?>" /></label></p>
<p><label for="<?php echo $this->get_field_id('googlep'); ?>"><?php echo __('Google+ link'); ?>: <input class="widefat" id="<?php echo $this->get_field_id('googlep'); ?>" name="<?php echo $this->get_field_name('googlep'); ?>" type="text" value="<?php echo attribute_escape($googlep); ?>" /></label></p>
<p><label for="<?php echo $this->get_field_id('linkedin'); ?>"><?php echo __('Linkedin link'); ?>: <input class="widefat" id="<?php echo $this->get_field_id('linkedin'); ?>" name="<?php echo $this->get_field_name('linkedin'); ?>" type="text" value="<?php echo attribute_escape($linkedin); ?>" /></label></p>
<p><label for="<?php echo $this->get_field_id('dribbble'); ?>"><?php echo __('Dribbble link'); ?>: <input class="widefat" id="<?php echo $this->get_field_id('dribbble'); ?>" name="<?php echo $this->get_field_name('dribbble'); ?>" type="text" value="<?php echo attribute_escape($dribbble); ?>" /></label></p>
<p><label for="<?php echo $this->get_field_id('flickr'); ?>"><?php echo __('Flickr link'); ?>: <input class="widefat" id="<?php echo $this->get_field_id('flickr'); ?>" name="<?php echo $this->get_field_name('flickr'); ?>" type="text" value="<?php echo attribute_escape($flickr); ?>" /></label></p>
<p><label for="<?php echo $this->get_field_id('description'); ?>"><?php echo __('Description'); ?>:<?php echo __('(For a new line type \\n)'); ?> <textarea rows='10' class="widefat" id="<?php echo $this->get_field_id('description'); ?>" name="<?php echo $this->get_field_name('description'); ?>"  ><?php echo attribute_escape($description); ?></textarea></label></p>